services:
  ydb:
    image: ydbplatform/local-ydb:latest
    container_name: ydbjs-drizzle-adapter-ydb
    hostname: localhost
    platform: linux/amd64
    ports:
      - '2135:2135'
      - '2136:2136'
      - '8765:8765'
      - '9092:9092'
    environment:
      GRPC_TLS_PORT: 2135
      GRPC_PORT: 2136
      MON_PORT: 8765
      YDB_KAFKA_PROXY_PORT: 9092
    volumes:
      - ./ydb_data:/ydb_data
      - ./ydb_certs:/ydb_certs
    healthcheck:
      disable: true
